version: 2.1
executors:
  docker-executor:
    docker:
      - image: aseelibrahimm/docker-terraform-awscli-ansible-ssh:v1
jobs:
  clone-git-code:
    executor: docker-executor
    steps:
      - checkout                
      - run:
          name: "Plan terraform"
          working_directory: Terraform
          command: |
            terraform init
            terraform plan --var-file=devops.tfvars
            
  apply-terraform:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: "apply terraform if approved"
          working_directory: Terraform
          command: |
            terraform init
            # echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $BASH_ENV
            # echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $BASH_ENV
            # aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            # aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure list
            terraform apply --var-file=devops.tfvars -auto-approve
            ls
            pwd
            chmod 400 tfproject.pem
    
      - run:
          name: "Build & Push The Docker Image To Docker Hub"
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKER_PASSWORD
            
      - run:
          name: "Run ansible file to deploy the container to ec2"
          working_directory: Ansible
          command: |
            ls
            cat inventory
            ansible-playbook -i inventory -e "CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME" config-EC2.yml
            cat ~/.ssh/config 
  destroy-terraform:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: "Destroy terraform resources if approved"
          working_directory: terraform
          command: |
            terraform init
            terraform destroy --var-file=devops.tfvars -auto-approve     
      
workflows:
  version: 2
  build:
    jobs:
      - clone-git-code
      - hold-to-apply:
          type: approval
          requires:
            - clone-git-code
      - apply-terraform:
          requires:
            - hold-to-apply
      - hold-to-destroy:
          type: approval
          requires:
            - apply-terraform
      - destroy-terraform:
          requires:
            - hold-to-destroy
