- name: play
  become: true
  gather_facts: true
  hosts: EC2
  tasks:
    - name: Update APT package manager repositories cache
      apt:
        update_cache: yes


    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install docker-compose
      remote_user: ubuntu
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
    
    - name: Copy dockerfile to the remote server
      synchronize:
        src: ../Dockerfile
        dest: .

    - name: Copy docker compose file to the remote server
      copy:
        src: ../docker-compose.yaml
        dest: .

    - name: Copy app to the remote server
      copy:
        src: ../app
        dest: .

    - name: run docker compose
      community.docker.docker_compose:
        project_src: ../
        files:
        - docker-compose.yml
